{
	"documenttitle": {
		"text": "Red Hat Security Advisory: Red Hat OpenStack Platform 16.1.9 (python-django20) security update",
		"lang": "en"
	},
	"DocumentType": "Security Advisory",
	"documentpublisher": {
		"type": "Vendor",
		"ContactDetails": "secalert@redhat.com",
		"IssuingAuthority": "Red Hat Product Security"
	},
	"documenttracking": {
		"identification": {
			"ID": "RHSA-2022:8872"
		},
		"Status": "Final",
		"Version": "1",
		"revisionhistory": {
			"revision": {
				"Number": "1",
				"Date": "2022-12-07T20:29:00Z",
				"Description": "Current version"
			}
		},
		"InitialReleaseDate": "2022-12-07T20:29:00Z",
		"CurrentReleaseDate": "2022-12-07T20:29:00Z",
		"generator": {
			"Engine": "Red Hat SDEngine 3.10.0",
			"Date": "2022-12-08T05:03:00Z"
		}
	},
	"documentnotes": {
		"note": [
			{
				"text": "\nAn update for python-django20 is now available for Red Hat OpenStack\nPlatform 16.1.9 (Train) for Red Hat Enterprise Linux (RHEL) 8.2.\n\nRed Hat Product Security has rated this update as having a security impact\nof Important. A Common Vulnerability Scoring System (CVSS) base score,\nwhich gives a detailed severity rating, is available for each vulnerability\nfrom the CVE link(s) in the References section.\n    ",
				"title": "Topic",
				"type": "Summary",
				"ordinal": "1",
				"lang": "en"
			},
			{
				"text": "\nSecurity Fix(es):\n\n* SQL injection in QuerySet.annotate() aggregate() and extra()\n(CVE-2022-28346)\n\n* Possible XSS via '{% debug %}' template tag (CVE-2022-22818)\n\n* Denial of service possibility in file uploads (CVE-2022-23833)\n\nFor more details about the security issue(s), including the impact, a CVSS\nscore, acknowledgments, and other related information, refer to the CVE\npage listed in the References section.\n    ",
				"title": "Details",
				"type": "General",
				"ordinal": "2",
				"lang": "en"
			},
			{
				"text": "This content is licensed under the Creative Commons Attribution 4.0 International License (https://creativecommons.org/licenses/by/4.0/). If you distribute this content, or a modified version of it, you must provide attribution to Red Hat Inc. and provide a link to the original.",
				"title": "Terms of Use",
				"type": "Legal Disclaimer",
				"ordinal": "3",
				"lang": "en"
			}
		]
	},
	"documentdistribution": {
		"text": "Copyright Â© 2022 Red Hat, Inc. All rights reserved.",
		"lang": "en"
	},
	"aggregateseverity": {
		"text": "Important",
		"namespace": "https://access.redhat.com/security/updates/classification/"
	},
	"documentreferences": {
		"reference": [
			{
				"type": "Self",
				"URL": "https://access.redhat.com/errata/RHSA-2022:8872",
				"Description": "https://access.redhat.com/errata/RHSA-2022:8872"
			},
			{
				"type": "External",
				"URL": "https://access.redhat.com/security/updates/classification/#important",
				"Description": "https://access.redhat.com/security/updates/classification/#important"
			}
		]
	},
	"vulnerability": [
		{
			"ordinal": "1",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "django: Possible XSS via '{% debug %}' template tag",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-02-01T08:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-22818",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:8872"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-22818",
						"Description": "CVE-2022-22818"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2048775",
						"Description": "bz#2048775: CVE-2022-22818 django: Possible XSS via '{% debug %}' template tag"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-01-25T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"8Base-RHOS-16.1:python-django20-0:2.0.13-18.el8ost"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "2",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "django: Denial-of-service possibility in file uploads",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-02-01T08:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-23833",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:8872"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2022/feb/01/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-23833",
						"Description": "CVE-2022-23833"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2048778",
						"Description": "bz#2048778: CVE-2022-23833 django: Denial-of-service possibility in file uploads"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Moderate"
				}
			},
			"DiscoveryDate": "2022-01-25T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"8Base-RHOS-16.1:python-django20-0:2.0.13-18.el8ost"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		},
		{
			"ordinal": "3",
			"xmlns": "http://www.icasi.org/CVRF/schema/vuln/1.1",
			"notes": {
				"note": {
					"text": "Django: SQL injection in QuerySet.annotate(),aggregate() and extra()",
					"title": "Vulnerability Description",
					"type": "General",
					"ordinal": "1",
					"lang": "en"
				}
			},
			"ReleaseDate": "2022-04-11T08:00:00Z",
			"involvements": {
				"involvement": {
					"party": "Vendor",
					"status": "Completed"
				}
			},
			"CVE": "CVE-2022-28346",
			"remediations": {
				"remediation": {
					"type": "Vendor Fix",
					"description": {
						"text": "\nFor details on how to apply this update, which includes the changes\ndescribed in this advisory, refer to:\n\nhttps://access.redhat.com/articles/11258\n    ",
						"lang": "en"
					},
					"URL": "https://access.redhat.com/errata/RHSA-2022:8872"
				}
			},
			"references": {
				"reference": [
					{
						"URL": "https://www.djangoproject.com/weblog/2022/apr/11/security-releases/",
						"Description": "https://www.djangoproject.com/weblog/2022/apr/11/security-releases/"
					},
					{
						"URL": "https://access.redhat.com/security/cve/CVE-2022-28346",
						"Description": "CVE-2022-28346"
					},
					{
						"URL": "https://bugzilla.redhat.com/show_bug.cgi?id=2072447",
						"Description": "bz#2072447: CVE-2022-28346 Django: SQL injection in QuerySet.annotate(),aggregate() and extra()"
					}
				]
			},
			"threats": {
				"threat": {
					"type": "Impact",
					"Description": "Important"
				}
			},
			"DiscoveryDate": "2022-04-06T00:00:00Z",
			"productstatuses": {
				"status": {
					"type": "Fixed",
					"ProductID": [
						"8Base-RHOS-16.1:python-django20-0:2.0.13-18.el8ost"
					]
				}
			},
			"acknowledgments": {
				"acknowledgment": {
					"Description": ""
				}
			},
			"cvssscoresets": {
				"scoreset": {
					"BaseScore": "",
					"Vector": ""
				}
			}
		}
	],
	"producttree": {
		"xmlns": "http://www.icasi.org/CVRF/schema/prod/1.1",
		"branch": [
			{
				"type": "Product Family",
				"name": "Red Hat OpenStack Platform",
				"branch": [
					{
						"type": "Product Name",
						"name": "Red Hat OpenStack Platform 16.1",
						"fullproductname": {
							"text": "Red Hat OpenStack Platform 16.1",
							"productid": "8Base-RHOS-16.1",
							"cpe": "cpe:/a:redhat:openstack:16.1::el8"
						}
					}
				],
				"fullproductname": {}
			},
			{
				"type": "Product Version",
				"name": "python-django20-0:2.0.13-18.el8ost",
				"fullproductname": {
					"text": "python-django20-2.0.13-18.el8ost.src.rpm",
					"productid": "python-django20-0:2.0.13-18.el8ost",
					"cpe": "cpe:/a:redhat:openstack:16.1::el8"
				}
			}
		],
		"relationship": [
			{
				"productreference": "python-django20-0:2.0.13-18.el8ost",
				"relationtype": "Default Component Of",
				"relatestoproductreference": "8Base-RHOS-16.1",
				"fullproductname": {
					"text": "python-django20-0:2.0.13-18.el8ost as a component of Red Hat OpenStack Platform 16.1",
					"productid": "8Base-RHOS-16.1:python-django20-0:2.0.13-18.el8ost",
					"cpe": "cpe:/a:redhat:openstack:16.1::el8"
				}
			}
		]
	}
}
